In [2]:
x = [1,2,3,4,5,6,7,8,9]
id(x)

140292494417600

In [3]:
from sys import getsizeof as size
size(x)

136

In [4]:
136 + (8 * 8)

200

In [5]:
# import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9],dtype=np.int64,order="F") # fortran ordering
y = np.array([[1,2,3,4],[5,6,7,8]],dtype='i1')
print(size(x),x.dtype,x.ndim)
print(size(y),y.dtype,y.ndim)


184 int64 1
136 int8 2


np.int8 #i1
np.int16 #i2
np.int32 #i4
np.int64 #i8

np.float16 #f2
np.float32 #f4
np.float64 #f8

np.boolean # ?
np.object # 0


In [12]:
x = np.zeros((100,200,300))

In [13]:
x.ndim

3

In [14]:
x.shape

(100, 200, 300)

In [15]:
fream = np.zeros((600,800,3))

In [16]:
fream

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.zeros_like([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [3]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
np.clip(a,2,7)

array([2, 2, 2, 3, 4, 5, 6, 7, 7])

In [4]:
a = np.ones([3,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a = np.empty([1,255])
a

array([[6.92866025e-310, 6.92866025e-310, 2.09337669e-316,
        2.09337669e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.92864148e-310, 6.92864148e-310,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+00